### ISSUE TITLE
Failed to work with typescript: "Cannot find module 'http-status'"

### ISSUE THREAD

**Issue by idiotWu** [wdavidw/node-http-status#18]
While using the module with typescript as

```typescript
import * as HttpStatus from 'http-status';
```

It throws an error with `error TS2307: Cannot find module 'http-status'.`

I think this failure is caused by the `main` entry in [package.json](https://github.com/wdavidw/node-http-status/blob/master/package.json#L26), problem gets resolved once I change it into `main: ./lib/index.js`.

Though this is likely to be a bug of typescript itself (Microsoft/TypeScript#13484), it would be appreciated if you can do a quick fix :)

**Comment by wdavidw** [comment]
try now with version 0.2.5, main is now ""main": "lib/index.js""

**Comment by idiotWu** [comment]
Thanks!
